---

- name: burp2 servers
  become: yes
  become_method: sudo
  # environment: "{{ proxy_env }}"  # example to use behind proxy
  hosts: burp2_servers
  # Define the list of servers and add tags so you will be able to filter the call to a tag:
  roles: 
    - { role: CoffeeITWorks.burp2_server, tags: [ "burp2_server_all", "burp2_server" ] }

